"""v3_unified_uuid_schema

Revision ID: 1ceffa131b57
Revises: 
Create Date: 2026-05-08 20:07:16.665058
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1ceffa131b57'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
