"""switch_enum_to_string_final

Revision ID: 6fc90381e114
Revises: 1ceffa131b57
Create Date: 2026-05-09 19:46:18.498797
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6fc90381e114'
down_revision: str | None = '1ceffa131b57'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('internship_applications', 'platform',
               existing_type=postgresql.ENUM('leetcode', 'gfg', 'codeforces', 'other', name='platformtype'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('internship_applications', 'status',
               existing_type=postgresql.ENUM('identified', 'applied', 'assessment_received', 'assessment_submitted', 'interview_scheduled', 'interview_done', 'offer', 'rejected', 'ghosted', name='applicationstatus'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('internship_applications', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('identified', 'applied', 'assessment_received', 'assessment_submitted', 'interview_scheduled', 'interview_done', 'offer', 'rejected', 'ghosted', name='applicationstatus'),
               existing_nullable=True)
    op.alter_column('internship_applications', 'platform',
               existing_type=sa.String(),
               type_=postgresql.ENUM('leetcode', 'gfg', 'codeforces', 'other', name='platformtype'),
               existing_nullable=True)
    # ### end Alembic commands ###
